import Foundation

// this file was generated by Xcode-Better-Refactor-Tools
// https://github.com/tjarratt/xcode-better-refactor-tools

class FakeAyncMainQueueRunner : AyncMainQueueRunner, Equatable {
    init() {
    }

    private(set) var runOnMainQueueCallCount : Int = 0
    var runOnMainQueueStub : ((() -> ()) -> ())?
    private var runOnMainQueueArgs : Array<(() -> ())> = []
    func runOnMainQueueReturns(stubbedValues: ()) {
        self.runOnMainQueueStub = {(cb: () -&gt; ()) -> () in
            return stubbedValues
        }
    }
    func runOnMainQueueArgsForCall(callIndex: Int) -> (() -> ()) {
        return self.runOnMainQueueArgs[callIndex]
    }
    func runOnMainQueue(cb: () -&gt; ()) -> () {
        self.runOnMainQueueCallCount += 1
        self.runOnMainQueueArgs.append((cb))
        return self.runOnMainQueueStub!(cb)
    }

    static func reset() {
    }
}

func == (a: FakeAyncMainQueueRunner, b: FakeAyncMainQueueRunner) -> Bool {
    return a === b
}